# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'pruebaTecnica' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for pruebaTecnica
  pod 'Simple-Networking', '~> 0.3.2'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'NotificationBannerSwift', '~> 3.0.0'
  pod 'JWTDecode', '~> 3.0'
  pod 'PopupDialog', '~> 1.1'

end
